### ISSUE TITLE
PLEASE DO NOT PUT THE WEATHER API KEY INSIDE THE PYTHON SCRIPT

### ISSUE THREAD

**Issue by ninja-noodle** [Neela-krishna-5833/jarpy#1]
So when I forked your jarpy project and cloned it for contribution purposes, I noticed that "your weather api key" was included in the functions.py
**WHICH IS TOTALLY NOT RECOMMENDED AND NOT SAFE** especially if you are pushing those scripts to github where everyone can access your code freely.

The reason why it is not recommended is because
**It's your personal API key and you shouldn't let people to misuse it for their own**
**It can lead to some security vulnerabilities (eg. if your project is a very big, game-changing project, or if you are using a purchased API, people can freely use your API without your consent)
and many more reasons

Here's more information about it and how you can save those api keys: [Best Practices Python - Where to store API KEYS/TOKENS](https://stackoverflow.com/questions/56995350/best-practices-python-where-to-store-api-keys-tokens)

So, I hope you fix that API issue as soon as possible :D

**Comment by Neela-krishna-5833** [comment]
ok sir, but can you suggest me some other way?

**Comment by Neela-krishna-5833** [comment]
Sir, as suggested, I've placed the API key in the file and added it in gitignore

**Comment by Neela-krishna-5833** [comment]
I think the issue is solved and rectified. So, I'm closing the issue. If it was not still solved, please notify me...
Thank you
